version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: equipment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3407:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./it-storage-backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db:3306/equipment_db
    depends_on:
      - db

  frontend:
    build:
      context: ./it-storage-frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    depends_on:
      - backend

volumes:
  mysql_data: